# -*- coding: utf-8 -*-
"""Python(25.05.26).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PD_w6ShoXvBrgcacafu_EpKTpJHOOwgB
"""

#Factorial
a=int(input("Enter the  value:"))
fact=1
for i in range (1,a+1):
    fact=fact*i
print(fact)

#largest two digit
a=int(input("Enter the a value:"))
c=int(input("Enter the a value:"))
if a > c:
    print("A is greater")
else:
    print("C is greater")

#Palindrome
a=input("Enter the string:")
rev=a[::-1]
if(a==rev):
  print("Palindrome")
else:
  print("not palindrome")

#Armstrong
a=int(input("Enter the number: "))
order =len(str(a))
temp=a
sum=0
while temp > 0:
      digit=temp%10
      sum=sum+digit**order
      temp=temp//10
if(sum==a):
  print("Armstrong number")
else:
  print("not Armstrong")

#Prime numbers
a=50
print("Prime numbers from 1 to 50 are:")
for num in range(1, a):
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                break
        else:
            print(num, end=" ")

fahrenheit = float(input("Enter temperature in Fahrenheit: "))
celsius = (fahrenheit - 32) * 5 / 9
print("Temperature in Celsius =", celsius)

#Swap two digits without third variable
a=int(input("a="))
c=int(input("c="))
a,c=c,a
print("a=",a)
print("c=",c)

#Fibonacci Series
n = int(input("Enter number of terms: "))
a = 0
b = 1
print("Fibonacci Series:")
for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c

a,c,d=map(int,input().split())
print(a+c+d/3)
y

#Anagram
a=input()
c=input()
if(sorted(a)==sorted(c)):
  print("Anagram")
else:
  print("not Anagram")

# Find vowels and count them in a string
text = input("Enter a string: ")
vowels = "aeiouAEIOU"
count = 0
print("Vowels are:")
for char in text:
    if char in vowels:
        print(char)
        count += 1
print("Total number of vowels:", count)

#largest&smalllest
a=list((3,17,29,7,65,92))
c=max(a)
d=min(a)
print(c,d)

#calculator
a=int(input(""))
c=int(input(""))
print("Choose a method")
print("1.Addition")
print("2.Subtraction")
print("3.Multiplication")
print("4.Division")
d=int(input(""))
if(d==1):
  print("Addition:",a+c)
elif(d==2):
  print("Subtraction:",a-c)
elif(d==3):
  print("Multiplication:",a*c)
elif(d==4):
  print("Division:",a/c)

#gcd,lcm
"""
a=int(input("Enter the number:"))
c=int(input("Enter the number:"))
x=a
y=c
while y!=0:
  x,y=y,x%y
gcd=x
lcm=(a*c)//gcd
print("GCD",gcd)
print("LCM",lcm)
"""
a = int(input())
b = int(input())
x = a
y = b
while b != 0:
    a, b = b, a % b
gcd = a
print(gcd)
lcm = (x * y) / gcd
print(lcm)

#check positive,negative,zero
a=int(input("Enter the number:"))
if(a>0):
  print("Postive")
elif(a==0):
  print("Zero")
else:
  print("negative")

#odd or even
a=int(input("Enter the number:"))
if(a%2==0):
  print("Even")
else:
  print("Odd")

#leap year
year=int(input("Enter the year:"))
if(year%4==0 and year%100==0 or year%400==0):
  print("Leap year")
else:
  print("not leap year")

#pattern
for i in range(1,6):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

#left triangle pattern
for i in range(5,0,-1):
  for j in range(1,i+1):
    print("*",end=" ")
  print()

a=6
for i in range(a):
  print(" "*i+"*"*(a-i))

#diamond
n=3
for i in range(1,n+1):
  print(" "*(n-i)+"* "*i)
for i in range(n-1,0,-1):
  print(" "*(n-i)+"* "*i)

a=int(input("Enter a number"))
c=int(input("Enter a number"))
d=int(input("Enter a number"))
largest=max(a,c,d)
print(largest)

"""str1=input("Enter string1:")
str2=input("Enter string2:")
count=0
if len(str1)==len(str2):
  for i in range(len(str1)):
    for j in range(len(str2)):
      if str1[i]==str2[j]:
        count+=1
        break
  if count==len(str1):
    print("Strings are anagrams")
  else:
    print("Strings are not anagrams")

else:
  print("The strings are not anagrams")"""
s1 = input()
s2 = input()
if len(s1) == len(s2) and all(s1.count(i) == s2.count(i) for i in s1):
    print("Anagram")
else:
    print("Not Anagram")

n = int(input("Enter a number: "))

if n > 0 and (n & (n - 1)) == 0:
    print("Power of 2")
else:
    print("Not a Power of 2")

#Length of longest string without duplicates
s = input("Enter a string: ")
result = ""
for char in s:
    if char not in result:
        result += char

print(len(result))

#Palindrome substring and omit the other characters
s = input()
longest = ""
for i in range(len(s)):
    for j in range(i, len(s)):
        sub = s[i:j+1]
        if sub == sub[::-1]:
            if len(sub) > len(longest):
                longest = sub
print(longest)

#find the smallest positive integer
n=int(input())
arr=list(map(int,input().split()))
missing=1
while missing in arr:
  missing+=1
print(missing)

#check the differ in single character
s1=input()
s2=input()
if len(s1)!=len(s2):
  print("No")
else:
  count=0
  for i in range (len(s1)):
    if(s1[i]!=s2[i]):
      count+=1
    if count==1:
      print("Yes")
    else:
      print("No")

s = input()
vowels = "aeiouAEIOU"
v = ""
for ch in s:
    if ch in vowels:
        v += ch
v = v[::-1]
j = 0
result = ""
for ch in s:
    if ch in vowels:
        result += v[j]
        j += 1
    else:
        result += ch
print(result)

n = int(input())
rev = int(str(n)[::-1])
prime1 = True
prime2 = True
for i in range(2, n):
    if n % i == 0:
        prime1 = False
for i in range(2, rev):
    if rev % i == 0:
        prime2 = False
if prime1 and prime2:
    print("Both are prime")
else:
    print("No")

n=int(input())
for i in range(1,n+1):
  if(i%2==0):
    print(f"-{i}")
  else:
    print(i)

#missing sensor
n=int(input())
arr=set(map(int,input().split()))
missing=1
while missing in arr:
  missing+=1
print(missing)

#duplicate
arr = list(map(int, input().split()))
unique = []
for x in arr:
    if x not in unique:
        unique.append(x)

if len(arr) != len(unique):
    print("Duplicate Found")
else:
    print("No Duplicate")

#transaction
total=int(input())
withdraw=int(input())
if(withdraw<=total):
  rem=total-withdraw
  if rem>1000:
    print(rem)
  else:
    print("Transaction denied")
else:
  print("Transaction denied")

#
arr1=list(map(int,input().split()))
arr2=list(map(int,input().split()))
arr3=[]
for i in arr2:
  if i not in arr1:
    arr3.append(i)
print("Unauthorized user",arr3)

fuel=int(input())
payload=int(input())
if fuel>=5000 and payload<=1000:
  print("Launch Approved")
else:
  print("Launch Denied")

class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def total(self):
        return sum(self.marks)

    def average(self):
        return sum(self.marks) / len(self.marks)

    def highest_mark(self):
        return max(self.marks)
    def status(self):
        for mark in self.marks:
            if mark < 35:
                return "Fail"
        return "Pass"
s = Student("Ravi", [78, 45, 92, 30, 67])
print("Total:", s.total())
print("Average:", s.average())
print("Highest Mark:", s.highest_mark())
print("Status:", s.status())

class Employee:
    def __init__(self, name, scores):
        self.name = name
        self.scores = scores
    def best_score(self):
        return max(self.scores)
    def average_score(self):
        return round(sum(self.scores) / len(self.scores), 1)
    def months_above_80(self):
        count = 0
        for i in self.scores:
            if i > 80:
                count += 1
        return count
name = input("Employee Name: ")
scores = list(map(int, input("Scores: ").split()))
e = Employee(name, scores)
print("Best Score:", e.best_score())
print("Average Score:", e.average_score())
print("Months Above 80:", e.months_above_80())

class ParkingLot:
    def __init__(self, vehicles):
        self.vehicles = vehicles
    def find_duplicates(self):
        dup = []
        for i in self.vehicles:
            if self.vehicles.count(i) > 1 and i not in dup:
                dup.append(i)
        return dup
    def unique_vehicles(self):
        return len(set(self.vehicles))
vehicles = list(map(int,input().split()))
p = ParkingLot(vehicles)
print("Duplicate Vehicles:", p.find_duplicates())
print("Unique Vehicles:", p.unique_vehicles())

name=input()
scores=list(map(int,input().split()))
print("Best Score:",max(scores))
print("Average Score:",sum(scores)/len(scores))
print("Lowest Score:",min(scores))
count=0c
for i in scores:
  if i>50:
    count+=1
print(count)

#keyword analyzer
str1 = input().split()
str2 = input().split()
res = []
for key in str1:
    if key in str2:
        res.append(key)
if len(res) == len(str1) == len(str2):
    print("Equivalent Logs")
else:
    print("Different Logs")